class Config:
    CLIENT_ID = ""
    CLIENT_SECRET = ""
    STREAMER_LIST_LOCATION = ""
    DOWNLOAD_LOCATION = ""
    RECORDING_FINISHED_HOOK_SCRIPT = ""
    INFLUX_REPORTING_URL = ""
    INFLUX_LIVE_STREAMERS_REPORTING_PAYLOAD = ""
    TWITCH_OAUTH_TOKEN = ""
    REFRESH_INTERVAL = 60  # interval in seconds to refresh streams
