FROM python:3.9

RUN apt update && apt install -y streamlink git

RUN git clone https://github.com/chaz393/twitch-recording-manager.git
RUN pip install -r twitch-recording-manager/requirements.txt

COPY config.py /twitch-recording-manager/

CMD ["python3", "-u", "twitch-recording-manager/start_recording.py"]
